#!/usr/bin/env python3
"""Generate a narrow capability-free starter-plugin scaffold."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Generate a bounded starter-plugin scaffold for the capability-free "
            "local deterministic class."
        )
    )
    parser.add_argument(
        "--plugin-id",
        required=True,
        help="Plugin id shaped like plugin.<domain>.<name>",
    )
    parser.add_argument(
        "--authoring-class",
        required=True,
        choices=["capability_free_local_deterministic", "networked_read_only"],
        help="Starter-plugin authoring class to scaffold or refuse explicitly",
    )
    parser.add_argument(
        "--output-dir",
        required=True,
        help="Directory where the scaffold files should be written",
    )
    return parser.parse_args()


def validate_plugin_id(plugin_id: str) -> list[str]:
    parts = plugin_id.split(".")
    if len(parts) < 3 or parts[0] != "plugin" or any(not part for part in parts):
        raise SystemExit(
            "--plugin-id must be shaped like plugin.<domain>.<name> with no empty segments"
        )
    return parts


def write(path: Path, contents: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(contents, encoding="utf-8")


def manifest(
    plugin_id: str, tool_name: str, authoring_class: str, output_files: list[str]
) -> str:
    payload = {
        "schema_version": 1,
        "plugin_id": plugin_id,
        "tool_name": tool_name,
        "authoring_class": authoring_class,
        "bridge_exposed_default": False,
        "catalog_exposed_default": False,
        "generated_files": output_files,
    }
    return json.dumps(payload, indent=2) + "\n"


def runtime_snippet(
    plugin_id: str,
    tool_name: str,
    const_slug: str,
    schema_base: str,
    mount_envelope_id: str,
    runtime_bundle_id: str,
    runtime_bundle_ref: str,
    runtime_run_root_ref: str,
    manifest_id: str,
    artifact_id: str,
    type_name: str,
    snake: str,
) -> str:
    return f"""// Capability-free starter-plugin scaffold generated by
// `scripts/scaffold-tassadar-capability-free-starter-plugin.py`.
// TODO: copy the relevant pieces into
// `crates/psionic-runtime/src/tassadar_post_article_starter_plugin_runtime.rs`
// and replace every TODO with plugin-specific logic.

pub const STARTER_PLUGIN_{const_slug}_ID: &str = "{plugin_id}";
pub const STARTER_PLUGIN_{const_slug}_TOOL_NAME: &str = "{tool_name}";
pub const STARTER_PLUGIN_{const_slug}_INPUT_SCHEMA_ID: &str = "{schema_base}.input.v1";
pub const STARTER_PLUGIN_{const_slug}_OUTPUT_SCHEMA_ID: &str = "{schema_base}.output.v1";

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct {type_name}Request {{
    // TODO: replace the sample field set with plugin-specific request fields.
    pub text: String,
}}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct {type_name}Response {{
    // TODO: replace the sample field set with plugin-specific response fields.
    pub value: String,
}}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct {type_name}Config {{
    pub packet_size_limit_bytes: usize,
}}

impl Default for {type_name}Config {{
    fn default() -> Self {{
        Self {{
            packet_size_limit_bytes: 16 * 1024,
        }}
    }}
}}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct {type_name}InvocationOutcome {{
    pub receipt: StarterPluginInvocationReceipt,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub response: Option<{type_name}Response>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub refusal: Option<StarterPluginRefusal>,
}}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum {type_name}RuntimeCaseStatus {{
    ExactSuccess,
    TypedMalformedPacket,
    TypedRefusal,
}}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct {type_name}RuntimeCase {{
    pub case_id: String,
    pub status: {type_name}RuntimeCaseStatus,
    pub codec_id: String,
    pub request_packet_digest: String,
    pub response_or_refusal_schema_id: String,
    pub response_or_refusal_digest: String,
    pub receipt: StarterPluginInvocationReceipt,
    pub detail: String,
}}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct {type_name}RuntimeBundle {{
    pub schema_version: u16,
    pub bundle_id: String,
    pub plugin_id: String,
    pub plugin_version: String,
    pub manifest_id: String,
    pub artifact_id: String,
    pub packet_abi_version: String,
    pub mount_envelope_id: String,
    pub tool_projection: StarterPluginToolProjection,
    pub negative_claim_ids: Vec<String>,
    pub case_rows: Vec<{type_name}RuntimeCase>,
    pub claim_boundary: String,
    pub summary: String,
    pub bundle_digest: String,
}}

const {const_slug}_REFUSAL_SCHEMA_IDS: &[&str] = &[
    STARTER_PLUGIN_REFUSAL_SCHEMA_INVALID_ID,
    STARTER_PLUGIN_REFUSAL_PACKET_TOO_LARGE_ID,
    STARTER_PLUGIN_REFUSAL_UNSUPPORTED_CODEC_ID,
];

const {const_slug}_NEGATIVE_CLAIM_IDS: &[&str] = &[
    "todo_replace_with_plugin_specific_negative_claim_1",
    "todo_replace_with_plugin_specific_negative_claim_2",
];

pub const TASSADAR_POST_ARTICLE_PLUGIN_{const_slug}_RUNTIME_BUNDLE_REF: &str =
    "{runtime_bundle_ref}";
pub const TASSADAR_POST_ARTICLE_PLUGIN_{const_slug}_RUN_ROOT_REF: &str =
    "{runtime_run_root_ref}";

// TODO: add this row inside STARTER_PLUGIN_REGISTRATIONS.
const {const_slug}_REGISTRATION_TEMPLATE: StarterPluginRegistration = StarterPluginRegistration {{
    plugin_id: STARTER_PLUGIN_{const_slug}_ID,
    plugin_version: STARTER_PLUGIN_VERSION,
    tool_name: STARTER_PLUGIN_{const_slug}_TOOL_NAME,
    input_schema_id: STARTER_PLUGIN_{const_slug}_INPUT_SCHEMA_ID,
    success_output_schema_id: STARTER_PLUGIN_{const_slug}_OUTPUT_SCHEMA_ID,
    refusal_schema_ids: {const_slug}_REFUSAL_SCHEMA_IDS,
    replay_class_id: "deterministic_replayable",
    capability_class: StarterPluginCapabilityClass::LocalDeterministic,
    capability_namespace_ids: NO_CAPABILITY_NAMESPACE_IDS,
    negative_claim_ids: {const_slug}_NEGATIVE_CLAIM_IDS,
    mount_envelope_id: "{mount_envelope_id}",
    manifest_id: "{manifest_id}",
    artifact_id: "{artifact_id}",
    runtime_bundle_id: "{runtime_bundle_id}",
    runtime_bundle_ref: TASSADAR_POST_ARTICLE_PLUGIN_{const_slug}_RUNTIME_BUNDLE_REF,
    runtime_run_root_ref: TASSADAR_POST_ARTICLE_PLUGIN_{const_slug}_RUN_ROOT_REF,
    tool_description: "TODO: replace with one bounded capability-free tool description.",
    bridge_exposed: false,
    catalog_exposed: false,
    catalog: None,
}};

pub fn {snake}_tool_projection() -> StarterPluginToolProjection {{
    let registration = starter_plugin_registration(STARTER_PLUGIN_{const_slug}_ID);
    starter_plugin_tool_projection_from_registration(
        registration,
        serde_json::json!({{
            "type": "object",
            "additionalProperties": false,
            "properties": {{
                "text": {{"type": "string"}}
            }},
            "required": ["text"]
        }}),
    )
}}

pub fn invoke_{snake}_json_packet(
    codec_id: &str,
    packet: &[u8],
    config: &{type_name}Config,
) -> {type_name}InvocationOutcome {{
    let _ = (codec_id, packet, config);
    // TODO: implement decode, typed refusal, success response, and receipt creation.
    todo!("implement invoke_{snake}_json_packet")
}}

pub fn build_{snake}_runtime_bundle() -> {type_name}RuntimeBundle {{
    // TODO: add success and refusal fixtures, then compute the stable digest.
    todo!("implement build_{snake}_runtime_bundle")
}}
"""


def example_bundle_writer(snake: str, example_file_name: str) -> str:
    return f"""use psionic_runtime::{{
    tassadar_post_article_plugin_{example_file_name}_runtime_bundle_path,
    write_{snake}_runtime_bundle,
}};

fn main() -> Result<(), Box<dyn std::error::Error>> {{
    let output_path = tassadar_post_article_plugin_{example_file_name}_runtime_bundle_path();
    let bundle = write_{snake}_runtime_bundle(&output_path)?;
    println!("wrote {{}} ({{}})", output_path.display(), bundle.bundle_digest);
    Ok(())
}}
"""


def test_snippet(snake: str, example_file_name: str) -> str:
    return f"""// TODO: merge these tests into the runtime test module in
// `crates/psionic-runtime/src/tassadar_post_article_starter_plugin_runtime.rs`.

#[test]
fn {example_file_name}_success_case_is_bounded_and_typed() {{
    // TODO: call invoke_{snake}_json_packet with one success packet and
    // assert the typed response fields plus output schema id.
}}

#[test]
fn {example_file_name}_runtime_bundle_matches_committed_truth() {{
    // TODO: compare build_{snake}_runtime_bundle() against the committed
    // fixture once the bundle writer lands.
}}
"""


def checker_script(example_file_name: str, function_slug: str, tool_name: str) -> str:
    return f"""#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${{BASH_SOURCE[0]}}")/.." && pwd)"
cd "$ROOT_DIR"

# TODO: update the package/example names after copying this scaffold into the repo.
cargo run -p psionic-runtime --example tassadar_post_article_{example_file_name}_bundle
cargo test -p psionic-runtime {example_file_name}_ -- --nocapture

jq -e '
  .tool_projection.tool_name == "{tool_name}"
  and .plugin_id != ""
  and .bundle_id != ""
' "TODO_REPLACE_WITH_RUNTIME_BUNDLE_PATH" >/dev/null
"""


def scaffold_readme(plugin_id: str, tool_name: str, output_files: list[str]) -> str:
    file_list = "\n".join(f"- `{name}`" for name in output_files)
    return f"""# Capability-Free Starter Plugin Scaffold

This directory was generated for:

- plugin id: `{plugin_id}`
- tool name: `{tool_name}`
- authoring class: `capability_free_local_deterministic`

It is a bounded scaffold, not a finished plugin.

Generated files:

{file_list}

How to use it:

1. copy the runtime snippet into
   `crates/psionic-runtime/src/tassadar_post_article_starter_plugin_runtime.rs`
2. replace every `TODO` with plugin-specific logic and negative claims
3. copy the example bundle writer into `crates/psionic-runtime/examples/`
4. merge the test stub into the runtime test module
5. copy the checker script into `scripts/`
6. decide explicitly whether the plugin should stay runtime-only or later be
   admitted to bridge, catalog, and controller surfaces

What it does not do:

- no automatic runtime-file patching
- no networked plugin scaffolding
- no automatic bridge, catalog, or controller admission
- no public publication or external binary support
"""


def main() -> None:
    args = parse_args()
    parts = validate_plugin_id(args.plugin_id)
    if args.authoring_class != "capability_free_local_deterministic":
        raise SystemExit(
            "networked_read_only is intentionally not scaffolded; "
            "networked starter plugins must keep mount, replay, and policy truth "
            "explicit through manual authoring"
        )
    name_parts = parts[1:]
    snake = "_".join(name_parts)
    tool_name = f"plugin_{snake}"
    const_slug = "_".join(part.upper() for part in name_parts)
    pascal = "".join(part.capitalize() for part in name_parts)
    schema_base = args.plugin_id
    example_file_name = snake
    output_dir = Path(args.output_dir)

    output_files = [
        "README.md",
        "scaffold_manifest.json",
        f"plugin_{snake}_runtime_snippet.rs",
        f"tassadar_post_article_{snake}_bundle.rs",
        f"plugin_{snake}_tests.rs",
        f"check-{snake}.sh",
    ]

    write(
        output_dir / "README.md",
        scaffold_readme(args.plugin_id, tool_name, output_files),
    )
    write(
        output_dir / "scaffold_manifest.json",
        manifest(args.plugin_id, tool_name, args.authoring_class, output_files),
    )
    write(
        output_dir / f"plugin_{snake}_runtime_snippet.rs",
        runtime_snippet(
            plugin_id=args.plugin_id,
            tool_name=tool_name,
            const_slug=const_slug,
            schema_base=schema_base,
            mount_envelope_id=f"mount.{args.plugin_id}.no_capabilities.v1",
            runtime_bundle_id=f"tassadar.post_article.{tool_name}.runtime_bundle.v1",
            runtime_bundle_ref=(
                f"fixtures/tassadar/runs/tassadar_post_article_{snake}_v1/"
                f"tassadar_post_article_{snake}_bundle.json"
            ),
            runtime_run_root_ref=(
                f"fixtures/tassadar/runs/tassadar_post_article_{snake}_v1"
            ),
            manifest_id=f"manifest.{args.plugin_id}.v1",
            artifact_id=f"artifact.{args.plugin_id}.v1",
            type_name=pascal,
            snake=snake,
        ),
    )
    write(
        output_dir / f"tassadar_post_article_{snake}_bundle.rs",
        example_bundle_writer(snake, example_file_name),
    )
    write(
        output_dir / f"plugin_{snake}_tests.rs",
        test_snippet(snake, example_file_name),
    )
    write(
        output_dir / f"check-{snake}.sh",
        checker_script(example_file_name, pascal, tool_name),
    )


if __name__ == "__main__":
    main()
